name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Gateway Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./gateway/Dockerfile
          push: true
          tags: |
            nishsatish/pingmemaybe:gateway

      - name: Build & Push Processor Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./processor/Dockerfile
          push: true
          tags: |
            nishsatish/pingmemaybe:processor